name: "yolo_object_detection"
platform: "onnxruntime_onnx"

max_batch_size: 32

input [
  {
    name: "images"
    data_type: TYPE_FP32
    dims: [ 3, 640, 640 ]
  }
]

output [
  {
    name: "output0"
    data_type: TYPE_FP32
    # Changed 8400 to -1 to match the dynamic ONNX export
    dims: [ 84, -1 ]
  }
]

dynamic_batching {
  preferred_batch_size: [4, 8, 16, 32]
  max_queue_delay_microseconds: 100000
}

instance_group [
  { kind: KIND_CPU count: 1 }
]